# Generated by Django 5.2.7 on 2025-11-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_folder', models.CharField(default='logs', max_length=255)),
                ('log_file', models.CharField(default='main.log', max_length=255)),
                ('debug_mode', models.BooleanField(default=False)),
                ('logo_name', models.CharField(default='logo.png', max_length=255)),
                ('save_folder_name', models.CharField(default='savedImages', max_length=255)),
                ('save_mode', models.BooleanField(default=True)),
                ('number_of_camera', models.IntegerField(default=1)),
                ('camera_ids', models.CharField(default='40649607', max_length=255)),
                ('exposure', models.IntegerField(default=10000)),
                ('classification_model', models.CharField(max_length=255)),
                ('resize_width', models.IntegerField(default=960)),
                ('resize_height', models.IntegerField(default=600)),
                ('bounding_box_thickness', models.IntegerField(default=10)),
                ('header_height', models.IntegerField(default=50)),
                ('plc_ip', models.GenericIPAddressField(default='192.168.0.1')),
                ('rack', models.IntegerField(default=0)),
                ('slot', models.IntegerField(default=1)),
                ('db_number', models.IntegerField(default=1)),
                ('byte_index', models.IntegerField(default=0)),
                ('bitindex_dict', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
